### ISSUE TITLE
form/multipart parser at Http Server side.

### ISSUE THREAD

**Issue by snahmad** [AndsonYe/MultipartEncoder#1]
Can this parser works for HttpServer/ listener?

**Comment by AndsonYe** [comment]
This parser is only for HttpClient usage.

**Comment by Coderx7** [comment]
@snahmad could you find anything for server side?

**Comment by elq81hc** [comment]
@Coderx7 I see https://github.com/yhirose/cpp-httplib/ support to parse multipart form data on server-side
