### ISSUE TITLE
std::strings are not deleted

### ISSUE THREAD

**Issue by Mogball** [AndsonYe/MultipartEncoder#4]
https://github.com/AndsonYe/MultipartEncoder/blob/3377874fe509d1cb2cd510cb44fdb7a42bf54c30/multipart_parser.cpp#L61

The pointers to `std::string` are being deleted, leading to a very fast memory leak (for a large number of files). The heap calls aren't even necessary since you could just put the strings on the stack.

**Comment by AndsonYe** [comment]
> https://github.com/AndsonYe/MultipartEncoder/blob/3377874fe509d1cb2cd510cb44fdb7a42bf54c30/multipart_parser.cpp#L61
> 
> The pointers to `std::string` are being deleted, leading to a very fast memory leak (for a large number of files). The heap calls aren't even necessary since you could just put the strings on the stack.

Thanks for bring it out. I fixed it in the latest commit.
