### ISSUE TITLE
error: conversion to ‘int’ from ‘size_t {aka long unsigned int}’ may alter its value [-Werror=conversion]

### ISSUE THREAD

**Issue by PiseyYou** [AndsonYe/MultipartEncoder#5]
first make error appead, after edit the file threadpool.h  from size_t num_threads to int num_thread, 

there  are still some ways to change, in the file threadpool.cpp, 
three place to change type size_t to int, then make -j4
but the error appead this:

```
error: no matching function for call to ‘make_shared(std::reference_wrapper<boost::asio::io_context>)’
```

is there any way to solve the make error?

**Comment by AndsonYe** [comment]
The error should result from the stale cpprestsdk submodule. I just changed the submodule to master branch. Pls update and try again.
