### ISSUE TITLE
nested

### ISSUE THREAD

**Issue by hdayvary** [AndsonYe/MultipartEncoder#6]
Hi
What if we need it in nested like in woocommerce image for product:
https://woocommerce.github.io/woocommerce-rest-api-docs/?php#create-a-product
that is :
[
    'name' => 'Premium Quality',
    'images' => [
        [
            'src' => 'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_front.jpg'
        ]
    ]
];

**Comment by AndsonYe** [comment]
This looks like posting raw text data in json format, not multipart-form data.
To post raw text data cppRestSdk can already do that. You don't need this lib

**Comment by hdayvary** [comment]
Thanks
but I need send image file to woocommerce.
If I can do it in cppRestSdk,  would you please send me some link or tell me where i can read about how to do it
Best regards

**Comment by AndsonYe** [comment]
Sorry got confused, the example you gave me is posting a json text that includes an image url, not sending the file itself.
By sending image file to woocommerce, what does the API look like? What do you mean by sending a file in a nested way?

**Comment by hdayvary** [comment]
our program is a windows application (Visual C++ 2019)
so we can not send local file path to a woocommerce in a host
so we need to send in some way like multipart/form-data

**Comment by hdayvary** [comment]
Sorry for confusing
woo commerce just receive image url
we wanted to test sending it in multipart/form-data way and if it works or not
but as you see it is in section named images (url is in images, nested)
so we can not handle it and we dont know how to solve it.
(we are thinking on ftp way(uploading in ftp and then sending url of it to woocommerce))
